spring:

  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${mail.companyname}    # 3
    password:  ${mail.password}
    properties:
      mail:
        smtp:
          auth: true # 5
          starttls:
            enable: true # 7

  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:data.sql
#    data: classpath:data.sql
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
#      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
#      mode: always
      mode: always
      encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8080