spring:
  servlet:
    multipart:
      enabled: true
      location: C:/SSAFY/enjoytripImg
      max-request-size: 30MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: sharedtripad@gmail.com    # 3
    password:  drbvimkhejowmezo
    properties:
      mail:
        smtp:
          auth: true # 5
          starttls:
            enable: true # 7

  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
#    data: classpath:data.sql
#    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
#      mode: always
#      mode: always
      encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
part4:
  upload:
    path: C:/Users/gkstj/Desktop/FINALPairPjt/enjoytrip/enjoytrip/src/main/resources/profileimg
server:
  port: 8080