spring:

  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

    data: classpath*:/data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql:
        format_sql:

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8080